spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recipe_db
    username: postgres
    password: postgres
    name: recipe_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api


credentials:
  user:
    username: user
    password: password
  admin:
    username: admin
    password: password